apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-yhhl
  namespace: jvm-build-nlsz-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rh_ee_tnevrlka/test-images@sha256:08677dd85f90a7704f4c10565900aa586fbff2ff80797ec90a5ac77d27b46711
        name: container-image
        resources: {}
status: {}
